export const countyNames = [
	{ value: "10", label: "ALBA" },
	{ value: "29", label: "ARAD" },
	{ value: "38", label: "ARGES" },
	{ value: "47", label: "BACAU" },
	{ value: "56", label: "BIHOR" },
	{ value: "65", label: "BISTRITA–NASAUD" },
	{ value: "74", label: "BOTOSANI" },
	{ value: "92", label: "BRAILA" },
	{ value: "83", label: "BRASOV" },
	{ value: "403", label: "BUCURESTI" },
	{ value: "109", label: "BUZAU" },
	{ value: "519", label: "CALARASI" },
	{ value: "118", label: "CARAS–SEVERIN" },
	{ value: "127", label: "CLUJ" },
	{ value: "136", label: "CONSTANTA" },
	{ value: "145", label: "COVASNA" },
	{ value: "154", label: "DAMBOVITA" },
	{ value: "163", label: "DOLJ" },
	{ value: "172", label: "GALATI" },
	{ value: "528", label: "GIURGIU" },
	{ value: "181", label: "GORJ" },
	{ value: "190", label: "HARGHITA" },
	{ value: "207", label: "HUNEDOARA" },
	{ value: "216", label: "IALOMITA" },
	{ value: "225", label: "IASI" },
	{ value: "234", label: "ILFOV" },
	{ value: "243", label: "MARAMURES" },
	{ value: "252", label: "MEHEDINTI" },
	{ value: "261", label: "MURES" },
	{ value: "270", label: "NEAMT" },
	{ value: "289", label: "OLT" },
	{ value: "298", label: "PRAHOVA" },
	{ value: "314", label: "SALAJ" },
	{ value: "305", label: "SATU MARE" },
	{ value: "323", label: "SIBIU" },
	{ value: "332", label: "SUCEAVA" },
	{ value: "341", label: "TELEORMAN" },
	{ value: "350", label: "TIMIS" },
	{ value: "369", label: "TULCEA" },
	{ value: "387", label: "VALCEA" },
	{ value: "378", label: "VASLUI" },
	{ value: "396", label: "VRANCEA" },
];

export const countiesMap: Record<string, string> = {
	"-1": "Selectați un județ din listă",
	"10": "ALBA",
	"29": "ARAD",
	"38": "ARGES",
	"47": "BACAU",
	"56": "BIHOR",
	"65": "BISTRITA–NASAUD",
	"74": "BOTOSANI",
	"92": "BRAILA",
	"83": "BRASOV",
	"403": "BUCURESTI",
	"109": "BUZAU",
	"519": "CALARASI",
	"118": "CARAS–SEVERIN",
	"127": "CLUJ",
	"136": "CONSTANTA",
	"145": "COVASNA",
	"154": "DAMBOVITA",
	"163": "DOLJ",
	"172": "GALATI",
	"528": "GIURGIU",
	"181": "GORJ",
	"190": "HARGHITA",
	"207": "HUNEDOARA",
	"216": "IALOMITA",
	"225": "IASI",
	"234": "ILFOV",
	"243": "MARAMURES",
	"252": "MEHEDINTI",
	"261": "MURES",
	"270": "NEAMT",
	"289": "OLT",
	"298": "PRAHOVA",
	"314": "SALAJ",
	"305": "SATU MARE",
	"323": "SIBIU",
	"332": "SUCEAVA",
	"341": "TELEORMAN",
	"350": "TIMIS",
	"369": "TULCEA",
	"387": "VALCEA",
	"378": "VASLUI",
	"396": "VRANCEA",
};
